### ISSUE TITLE
Réparer le timer de début du LAN

### ISSUE THREAD

**Issue by Moustachauve** [ADEPT-Informatique/LanAdept#18]
En ce moment, le timer de début du LAN va afficher des chiffres négatifs lorsqu'il tombera à zéro.

Ce serait bien de le caché lorsqu'il tombe à zéro, et peut-être même afficher des messages comme par exemple : Le LAN est débuté!

Si on affiche des messages pour le début du LAN, il faudrait aussi en afficher un pour dire que le LAN est terminé

**Comment by huideaki** [comment]
fixed
