### ISSUE TITLE
Optimisation de la map

### ISSUE THREAD

**Issue by island212** [ADEPT-Informatique/LanAdept#25]
Enlever une charge de téléchargement au serveur en optimisant la map. Surtout qu'on pourrait supposément en avoir plusieurs.

- [ ] Télécharger les noms des utilisateurs seulement quand l'utilisateur veut le voir (Ajax)
- [ ] Mettre la map en RAM.
- [ ] Enlever le model Tile et le mettre dans la place

**Comment by huideaki** [comment]
Fermeture du a l'implantation de l'API
