### ISSUE TITLE
Le scanner ne fonctionne pas pour les code barres avec des lettres

### ISSUE THREAD

**Issue by Moustachauve** [ADEPT-Informatique/LanAdept#44]
En ce moment, le script qui gère le scanner ne supporte pas les codes barres avec des chiffres à cause de cette ligne:
```if (e.which >= 48 && e.which <= 57) {```
( LanAdept/LanAdeptAdmin/Scripts/scanner.js )
48 à 57 sont les codes ascii pour 0 à 9 avec '/' pour une raison quelconque.
Il faudrait accepter les autres caractères aussi.

**Comment by huideaki** [comment]
j'ai ajouté de A-Z

**Comment by huideaki** [comment]
Ajout des tout les caractère possible a-z A-Z
